// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"gitlabhost.rtp.raleigh.ibm.com/spectrum-plugin/core"
)

type FakeSpectrumClient struct {
	CreateFilesetStub        func(fileset *core.Fileset) error
	createFilesetMutex       sync.RWMutex
	createFilesetArgsForCall []struct {
		fileset *core.Fileset
	}
	createFilesetReturns struct {
		result1 error
	}
	RemoveFilesetStub        func(fileset *core.Fileset) error
	removeFilesetMutex       sync.RWMutex
	removeFilesetArgsForCall []struct {
		fileset *core.Fileset
	}
	removeFilesetReturns struct {
		result1 error
	}
	LinkFilesetStub        func(fileset *core.Fileset) (string, error)
	linkFilesetMutex       sync.RWMutex
	linkFilesetArgsForCall []struct {
		fileset *core.Fileset
	}
	linkFilesetReturns struct {
		result1 string
		result2 error
	}
	UnlinkFilesetStub        func(fileset *core.Fileset) error
	unlinkFilesetMutex       sync.RWMutex
	unlinkFilesetArgsForCall []struct {
		fileset *core.Fileset
	}
	unlinkFilesetReturns struct {
		result1 error
	}
	ListFilesetsStub        func() ([]core.Fileset, error)
	listFilesetsMutex       sync.RWMutex
	listFilesetsArgsForCall []struct{}
	listFilesetsReturns     struct {
		result1 []core.Fileset
		result2 error
	}
	ListFilesetStub        func(fileset string) (*core.Fileset, error)
	listFilesetMutex       sync.RWMutex
	listFilesetArgsForCall []struct {
		fileset string
	}
	listFilesetReturns struct {
		result1 *core.Fileset
		result2 error
	}
	IsMountedStub        func() (bool, error)
	isMountedMutex       sync.RWMutex
	isMountedArgsForCall []struct{}
	isMountedReturns     struct {
		result1 bool
		result2 error
	}
	MountStub        func() error
	mountMutex       sync.RWMutex
	mountArgsForCall []struct{}
	mountReturns     struct {
		result1 error
	}
}

func (fake *FakeSpectrumClient) CreateFileset(fileset *core.Fileset) error {
	fake.createFilesetMutex.Lock()
	fake.createFilesetArgsForCall = append(fake.createFilesetArgsForCall, struct {
		fileset *core.Fileset
	}{fileset})
	fake.createFilesetMutex.Unlock()
	if fake.CreateFilesetStub != nil {
		return fake.CreateFilesetStub(fileset)
	} else {
		return fake.createFilesetReturns.result1
	}
}

func (fake *FakeSpectrumClient) CreateFilesetCallCount() int {
	fake.createFilesetMutex.RLock()
	defer fake.createFilesetMutex.RUnlock()
	return len(fake.createFilesetArgsForCall)
}

func (fake *FakeSpectrumClient) CreateFilesetArgsForCall(i int) *core.Fileset {
	fake.createFilesetMutex.RLock()
	defer fake.createFilesetMutex.RUnlock()
	return fake.createFilesetArgsForCall[i].fileset
}

func (fake *FakeSpectrumClient) CreateFilesetReturns(result1 error) {
	fake.CreateFilesetStub = nil
	fake.createFilesetReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSpectrumClient) RemoveFileset(fileset *core.Fileset) error {
	fake.removeFilesetMutex.Lock()
	fake.removeFilesetArgsForCall = append(fake.removeFilesetArgsForCall, struct {
		fileset *core.Fileset
	}{fileset})
	fake.removeFilesetMutex.Unlock()
	if fake.RemoveFilesetStub != nil {
		return fake.RemoveFilesetStub(fileset)
	} else {
		return fake.removeFilesetReturns.result1
	}
}

func (fake *FakeSpectrumClient) RemoveFilesetCallCount() int {
	fake.removeFilesetMutex.RLock()
	defer fake.removeFilesetMutex.RUnlock()
	return len(fake.removeFilesetArgsForCall)
}

func (fake *FakeSpectrumClient) RemoveFilesetArgsForCall(i int) *core.Fileset {
	fake.removeFilesetMutex.RLock()
	defer fake.removeFilesetMutex.RUnlock()
	return fake.removeFilesetArgsForCall[i].fileset
}

func (fake *FakeSpectrumClient) RemoveFilesetReturns(result1 error) {
	fake.RemoveFilesetStub = nil
	fake.removeFilesetReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSpectrumClient) LinkFileset(fileset *core.Fileset) (string, error) {
	fake.linkFilesetMutex.Lock()
	fake.linkFilesetArgsForCall = append(fake.linkFilesetArgsForCall, struct {
		fileset *core.Fileset
	}{fileset})
	fake.linkFilesetMutex.Unlock()
	if fake.LinkFilesetStub != nil {
		return fake.LinkFilesetStub(fileset)
	} else {
		return fake.linkFilesetReturns.result1, fake.linkFilesetReturns.result2
	}
}

func (fake *FakeSpectrumClient) LinkFilesetCallCount() int {
	fake.linkFilesetMutex.RLock()
	defer fake.linkFilesetMutex.RUnlock()
	return len(fake.linkFilesetArgsForCall)
}

func (fake *FakeSpectrumClient) LinkFilesetArgsForCall(i int) *core.Fileset {
	fake.linkFilesetMutex.RLock()
	defer fake.linkFilesetMutex.RUnlock()
	return fake.linkFilesetArgsForCall[i].fileset
}

func (fake *FakeSpectrumClient) LinkFilesetReturns(result1 string, result2 error) {
	fake.LinkFilesetStub = nil
	fake.linkFilesetReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeSpectrumClient) UnlinkFileset(fileset *core.Fileset) error {
	fake.unlinkFilesetMutex.Lock()
	fake.unlinkFilesetArgsForCall = append(fake.unlinkFilesetArgsForCall, struct {
		fileset *core.Fileset
	}{fileset})
	fake.unlinkFilesetMutex.Unlock()
	if fake.UnlinkFilesetStub != nil {
		return fake.UnlinkFilesetStub(fileset)
	} else {
		return fake.unlinkFilesetReturns.result1
	}
}

func (fake *FakeSpectrumClient) UnlinkFilesetCallCount() int {
	fake.unlinkFilesetMutex.RLock()
	defer fake.unlinkFilesetMutex.RUnlock()
	return len(fake.unlinkFilesetArgsForCall)
}

func (fake *FakeSpectrumClient) UnlinkFilesetArgsForCall(i int) *core.Fileset {
	fake.unlinkFilesetMutex.RLock()
	defer fake.unlinkFilesetMutex.RUnlock()
	return fake.unlinkFilesetArgsForCall[i].fileset
}

func (fake *FakeSpectrumClient) UnlinkFilesetReturns(result1 error) {
	fake.UnlinkFilesetStub = nil
	fake.unlinkFilesetReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSpectrumClient) ListFilesets() ([]core.Fileset, error) {
	fake.listFilesetsMutex.Lock()
	fake.listFilesetsArgsForCall = append(fake.listFilesetsArgsForCall, struct{}{})
	fake.listFilesetsMutex.Unlock()
	if fake.ListFilesetsStub != nil {
		return fake.ListFilesetsStub()
	} else {
		return fake.listFilesetsReturns.result1, fake.listFilesetsReturns.result2
	}
}

func (fake *FakeSpectrumClient) ListFilesetsCallCount() int {
	fake.listFilesetsMutex.RLock()
	defer fake.listFilesetsMutex.RUnlock()
	return len(fake.listFilesetsArgsForCall)
}

func (fake *FakeSpectrumClient) ListFilesetsReturns(result1 []core.Fileset, result2 error) {
	fake.ListFilesetsStub = nil
	fake.listFilesetsReturns = struct {
		result1 []core.Fileset
		result2 error
	}{result1, result2}
}

func (fake *FakeSpectrumClient) ListFileset(fileset string) (*core.Fileset, error) {
	fake.listFilesetMutex.Lock()
	fake.listFilesetArgsForCall = append(fake.listFilesetArgsForCall, struct {
		fileset string
	}{fileset})
	fake.listFilesetMutex.Unlock()
	if fake.ListFilesetStub != nil {
		return fake.ListFilesetStub(fileset)
	} else {
		return fake.listFilesetReturns.result1, fake.listFilesetReturns.result2
	}
}

func (fake *FakeSpectrumClient) ListFilesetCallCount() int {
	fake.listFilesetMutex.RLock()
	defer fake.listFilesetMutex.RUnlock()
	return len(fake.listFilesetArgsForCall)
}

func (fake *FakeSpectrumClient) ListFilesetArgsForCall(i int) string {
	fake.listFilesetMutex.RLock()
	defer fake.listFilesetMutex.RUnlock()
	return fake.listFilesetArgsForCall[i].fileset
}

func (fake *FakeSpectrumClient) ListFilesetReturns(result1 *core.Fileset, result2 error) {
	fake.ListFilesetStub = nil
	fake.listFilesetReturns = struct {
		result1 *core.Fileset
		result2 error
	}{result1, result2}
}

func (fake *FakeSpectrumClient) IsMounted() (bool, error) {
	fake.isMountedMutex.Lock()
	fake.isMountedArgsForCall = append(fake.isMountedArgsForCall, struct{}{})
	fake.isMountedMutex.Unlock()
	if fake.IsMountedStub != nil {
		return fake.IsMountedStub()
	} else {
		return fake.isMountedReturns.result1, fake.isMountedReturns.result2
	}
}

func (fake *FakeSpectrumClient) IsMountedCallCount() int {
	fake.isMountedMutex.RLock()
	defer fake.isMountedMutex.RUnlock()
	return len(fake.isMountedArgsForCall)
}

func (fake *FakeSpectrumClient) IsMountedReturns(result1 bool, result2 error) {
	fake.IsMountedStub = nil
	fake.isMountedReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeSpectrumClient) Mount() error {
	fake.mountMutex.Lock()
	fake.mountArgsForCall = append(fake.mountArgsForCall, struct{}{})
	fake.mountMutex.Unlock()
	if fake.MountStub != nil {
		return fake.MountStub()
	} else {
		return fake.mountReturns.result1
	}
}

func (fake *FakeSpectrumClient) MountCallCount() int {
	fake.mountMutex.RLock()
	defer fake.mountMutex.RUnlock()
	return len(fake.mountArgsForCall)
}

func (fake *FakeSpectrumClient) MountReturns(result1 error) {
	fake.MountStub = nil
	fake.mountReturns = struct {
		result1 error
	}{result1}
}

var _ core.SpectrumClient = new(FakeSpectrumClient)
